# Generated by Django 3.2 on 2021-06-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeram', '0003_rename_clipping_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='image',
        ),
    ]
