# Generated by Django 3.2 on 2021-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeram', '0005_auto_20210620_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='author',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
